# $Id$
#
# Makefile for Hooch, Turner, Camille, and general docs, BSD Make version.
#
# Probably the best idea is to create a wrapper Makefile for other platforms,
#  as BSD Makefile structure is extremely elegant.
#

SUBDIR=		hooch
SUBDIR+=	turner
SUBDIR+=	camille
#SUBDIR+=	docs	# Avoid annoying popup of created dvi files

.include <bsd.subdir.mk>
