# $Id$
#
# Makefile for Camille, BSD Make version.
#
# Probably the best idea is to create a wrapper Makefile for other platforms,
#  as BSD Makefile structure is extremely elegant.
#

SUBDIR=		camille
SUBDIR+=	test

.include <bsd.subdir.mk>
