# $Id$
#
# Makefile for Hooch, BSD Make version.
#
# Probably the best idea is to create a wrapper Makefile for other platforms,
#  as BSD Makefile structure is extremely elegant.
#

SUBDIR=		src

.include <bsd.subdir.mk>
