# $Id$
#
# Makefile for Gune, BSD Make version.
#
# Probably the best idea is to create a wrapper Makefile for other platforms,
#  as BSD Makefile structure is extremely elegant.
#

SUBDIR=		src test

.include <bsd.subdir.mk>
